version: '3.8'

services:

  mongo:
    image: mongo:4.4.18
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - /home/pi/price_alarm/mongo_volume:/data/db
